/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./CloakRFP.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { CloakRFP } from "~~/contracts/CloakRFP";`
 */
import { CloakRFP as CloakRFP_LOCAL } from "./CloakRFP.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {} as const;

export const CloakRFP = {
  ...REMOTE,
  ...CloakRFP_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
